name: gh-actions-test
on: push:
jobs:
  build:
  runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2  
    - run: echo "Hello, world!"
    - run: |
        echo "This is a multi-line script."
        echo "You can run multiple commands here."
    