name: ci
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*api/.*

          VALIDATE_JSCPD: false
          VALIDATE_CHECKOV: false
          VALIDATE_BASH: false
          VALIDATE_TERRAFORM_TERRASCAN: false

          VALIDATE_CSHARP: true
          VALIDATE_DOCKERFILE: true
  build:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: ./api/api.csproj
      - run: dotnet restore
      - run: dotnet build --no-restore
      # could use artifacts here but the project is too small to justify it
  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: ./api/api.csproj
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --no-restore
